apiVersion: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      tracesToProfiles:
        datasourceUid: pyroscope
        tags:
          - service.name
          - stage
          - symbol
        profileTypeId: process_cpu:cpu:nanoseconds:cpu:nanoseconds

  - name: Pyroscope
    uid: pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040
    jsonData:
      keepCookies: []
