apiVersion: 1
prune: true

datasources:
  - name: Stock Postgres
    uid: stock-postgres
    type: postgres
    access: proxy
    url: $POSTGRES_HOST:$POSTGRES_PORT
    database: $POSTGRES_DB
    user: $POSTGRES_USER
    editable: false
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: $POSTGRES_DB
      sslmode: $POSTGRES_SSLMODE
      postgresVersion: 1600
      timescaledb: false
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
