apiVersion: 1

datasources:
  - name: Stock Postgres
    uid: stock-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: stockdash
    user: stock
    secureJsonData:
      password: stock
    jsonData:
      database: stockdash
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
